In [ ]:
import numpy as np
import random


R = np.array([
    [-1, -1, -1, -1,  0,  -1],
    [-1, -1, -1,  0, -1, 100],
    [-1, -1, -1,  0, -1,  -1],
    [-1,  0,  0, -1,  0, 100],
    [ 0, -1, -1,  0, -1, 100],
    [-1,  0, -1,  0,  0, 100]
])

print("Reward Matrix R:")
print(R)

Reward Matrix R:
[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0 100]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1   0   0 100]]


In [ ]:

Q = np.zeros_like(R, dtype=float)

gamma = 0.8

print("\nInitial Q-table:")
print(Q)


Initial Q-table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# -------------------------------------------------------
# STEP 3: Q-Learning Training
# -------------------------------------------------------

episodes = 1000

for episode in range(episodes):

    current_state = random.randint(0, 5)

    while current_state != 5:

        # Find allowed actions
        possible_actions = np.where(R[current_state] >= 0)[0]

        # Randomly select one allowed action
        next_state = random.choice(possible_actions)

        # Find possible actions from next state
        next_possible_actions = np.where(R[next_state] >= 0)[0]

        # Maximum future Q value
        max_future_Q = np.max(Q[next_state, next_possible_actions])

        # Q-learning update
        Q[current_state, next_state] = (
            R[current_state, next_state]
            + gamma * max_future_Q
        )

        current_state = next_state

In [ ]:


Q_normalized = Q / np.max(Q) * 100

print("\nLearned Q-table:")
print(np.round(Q_normalized, 1))


Learned Q-table:
[[  0.   0.   0.   0.  80.   0.]
 [  0.   0.   0.  80.   0. 100.]
 [  0.   0.   0.  80.   0.   0.]
 [  0.  80.  64.   0.  80. 100.]
 [ 64.   0.   0.  80.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]
